name: GitHub Traffic Analytics

on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch traffic data
        uses: jgehrcke/github-repo-stats@main
        env:
          GHRS_GITHUB_API_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
